version: 2

workflows:
  version: 2
  build:
    jobs:
      - build
  container-image:
    jobs:
      - container_image:
          filters:
            branches:
              only:
                - master
  container-image-release:
    jobs:
      - container_image_release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

jobs:
  build:
    docker:
      - image: cimg/go:1.24 # We shell out to git in tests, and circleci/golang should have it installed.

    working_directory: ~/telegraf-operator # Doesn't need to be in GOPATH since it's a Go module.

    environment:
      GOCACHE: /tmp/go-cache
      GOFLAGS: '-mod=readonly -p=8' # Go on Circle thinks 32 CPUs are available, but there aren't.

      # Set environment variables instead of touching global git config.
      # Without these set, some commands (like git am) will fail due to unknown user names.
      GIT_AUTHOR_NAME: circleci
      GIT_COMMITTER_NAME: circleci

    steps:
      - checkout

      # Populate GOCACHE.
      - restore_cache:
          name: Restoring GOCACHE
          keys:
            - telegraf-operator-gocache-{{ .Branch }}-{{ .Revision }} # Matches when retrying a single run.
            - telegraf-operator-gocache-{{ .Branch }}- # Matches a new commit on an existing branch.
            - telegraf-operator-gocache- # Matches a new branch.
      # Populate GOPATH/pkg.
      - restore_cache:
          name: Restoring GOPATH/pkg/mod
          keys:
            - telegraf-operator-gomod-{{ checksum "go.sum" }} # Matches based on go.sum checksum.

      # Build the binaries for the integration tests.
      - run: go build -race
      # The actual test.
      - run: go test -v -race ./...

      # Save the caches.
      - save_cache:
          name: Saving GOCACHE
          key: telegraf-operator-gocache-{{ .Branch }}-{{ .Revision }}
          paths:
            - /tmp/go-cache
          when: always
      - save_cache:
          name: Saving GOPATH/pkg/mod
          key: telegraf-operator-gomod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
          when: always
  container_image:
    # using a full VM is needed to build multi-arch container images
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Docker build and push using SHA
          command: |
            export DOCKER_BUILDKIT=1
            IMAGE="quay.io/influxdb/telegraf-operator"
            docker login -u "$QUAY_USER" -p "$QUAY_PASS" quay.io

            # create a new builder to support multi-arch images as the default builder doesn't support it
            docker buildx create --name "multiarch" || true
            docker buildx use "multiarch"

            # build image
            docker buildx build \
              --output=type=registry \
              --platform linux/amd64,linux/arm64,linux/arm/v7 \
              --tag "$IMAGE:$CIRCLE_SHA1" \
              --file Dockerfile.multi-arch .
  container_image_release:
    # using a full VM is needed to build multi-arch container images
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Docker build and push using release tag
          command: |
            export DOCKER_BUILDKIT=1
            IMAGE="quay.io/influxdb/telegraf-operator"
            docker login -u "$QUAY_USER" -p "$QUAY_PASS" quay.io

            # create a new builder to support multi-arch images as the default builder doesn't support it
            docker buildx create --name "multiarch" || true
            docker buildx use "multiarch"

            # build image
            docker buildx build \
              --output=type=registry \
              --platform linux/amd64,linux/arm64,linux/arm/v7 \
              --tag "$IMAGE:$CIRCLE_TAG" \
              --tag "$IMAGE:latest" \
              --file Dockerfile.multi-arch .
