apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
      annotations:
        telegraf.influxdata.com/ports: "8080"
        telegraf.influxdata.com/namepass: "['go_info','hello_processed_total','go_memstats*']"
    spec:
      containers:
      - name: hello-world
        image: okteto/hello-world:golang-metrics
